---
roles:
  - name: "linux-system-roles.podman"
    version: "1.8.3"
  - name: "linux-system-roles.journald"
    version: "1.5.0"

collections:
  - name: "ansible.posix"
    version: "2.1.0"
  - name: "containers.podman"
    version: "1.17.0"
  - name: "fedora.linux_system_roles"
    version: "1.109.0"
