---
- name: Configure Restic Backup
  hosts: home
  tasks:
    - name: Install restic
      become: true
      ansible.builtin.package:
        name: "restic"
        state: "present"

    - name: Create backup script
      ansible.builtin.template:
        src: "{{ project_dir }}/templates/backup.sh.j2"
        dest: "{{ ansible_user_dir }}/.local/bin/backup.sh"
        mode: "0755"

    - name: Create systemd service for restic backup
      ansible.builtin.template:
        src: "{{ project_dir }}/templates/restic-backup.service.j2"
        dest: "{{ ansible_user_dir }}/.config/systemd/user/restic-backup.service"
        mode: "0644"
      notify: Reload systemd

    - name: Create systemd timer for restic backup
      ansible.builtin.copy:
        dest: "{{ ansible_user_dir }}/.config/systemd/user/restic-backup.timer"
        mode: "0644"
        content: |
          [Unit]
          Description=Run restic backup weekly

          [Timer]
          OnCalendar=weekly
          Persistent=true

          [Install]
          WantedBy=timers.target
      notify: Reload systemd

    - name: Create systemd service for backup failure handler
      ansible.builtin.template:
        src: "{{ project_dir }}/templates/restic-backup-failure.service.j2"
        dest: "{{ ansible_user_dir }}/.config/systemd/user/restic-backup-failure.service"
        mode: "0644"
      notify: Reload systemd

    - name: Enable and start the backup timer
      ansible.builtin.systemd_service:
        name: "restic-backup.timer"
        enabled: true
        state: "started"
        scope: user
        daemon_reload: true

  handlers:
    - name: Reload systemd
      ansible.builtin.systemd_service:
        scope: user
        daemon_reload: true
